### ISSUE TITLE
关于redis-cerberus的高可用

### ISSUE THREAD

**Issue by saga1015** [HunanTV/redis-cerberus#15]
你好，请问redis-cerberus支持HA？或者redis-cerberus+keepliaved的方案是否可行，还请赐教

**Comment by neuront** [comment]
没试过 keepalived, 可以用 supervisor 跑.

**Comment by saga1015** [comment]
恩，用supervisor做进程级别的监控，也是一种办法
如果使用              haproxy
   -----------------------|------------------------
redis-cerberus                                    redis-cerberus
的方式应该也可以吧？

**Comment by neuront** [comment]
HAProxy 应该是可以用的

**Comment by saga1015** [comment]
好的，我们先测试下，有问题再请教，感谢neuront ;-)

**Comment by saga1015** [comment]
顺便问下，redis-cerberus只支持redis 3.0么？对2.8不支持？

**Comment by neuront** [comment]
只支持 3.0 cluster_enabled:1 的 redis 组建的集群
