### ISSUE TITLE
redis-cerberus 与cluster的性能对比，损耗多少？

### ISSUE THREAD

**Issue by andyli029** [HunanTV/redis-cerberus#18]

**Comment by neuront** [comment]
@andyli029 没有单独与直连 cluster 进行性能对比, 因为 [redis-benchmark 不支持集群](https://github.com/antirez/redis/issues/2191). 如果觉得慢, 请更新客户端或者库直连 redis cluster.

**Comment by andyli029** [comment]
redis-cerberus性能能达到多少？

**Comment by andyli029** [comment]
单点 redis-server 和 cerberus 8 核; 内存 64G，的IOPS是多少？

**Comment by neuront** [comment]
@andyli029 因素很多, 看操作, 网络也可能是瓶颈. redis-cerberus 支持大部分 redis-benchmark 的测试, 你可以搭好集群后用类似下面的方式测试.

    redis-benchmark -h 127.0.0.1 -p 8889 -P 10 -t get,set,lrange -c 500 -d 1000 -l -q

**Comment by andyli029** [comment]
就是简单的set,get，你们那边的测试性能是多少呢？我还要找机器centos7编译包，可以把大体的测试结果告诉我一下。

**Comment by neuront** [comment]
3 redis 2 线程 `-P 10`
* `-c 100 -d 1000` SET 380k/s GET 390k/s
* `-c 100 -d 10000` SET 68k/s GET 55k/s

**Comment by andyli029** [comment]
不带-P呢？看看多少？

**Comment by andyli029** [comment]
3 redis 2 线程是啥意思呢？

**Comment by neuront** [comment]
3 个 redis 主节点构成的集群, cerberus 开 2 线程
