### ISSUE TITLE
redis-cerberus 延时怎么样？和单机的redis相比，损耗多少？

### ISSUE THREAD

**Issue by andyli029** [HunanTV/redis-cerberus#24]

**Comment by neuront** [comment]
有一次 TCP 传输延时 (以及相应的网络延时). 由于 Redis 本身已经非常快了, 在低压力下的损耗是非常可观的, 大约有 20%-40% 左右, 高并发或者高 pipeline 的情况下降低到 5% - 25% (视不同指令而定). 对性能非常敏感的应用应当自行在客户端支持 redis 集群并直连.
